### ISSUE TITLE
Implement error handling on all input boxes

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/ux#28]
_NOTE: FIELD SPECIFIC IN-LINE ERROR COPY TO BE PROVIDED FOR 2.5 RELEASE_

- [ ] Submit button should remain in disabled state until all required inputs are present and/or errors addressed by listening for onChange
- [ ] All required input boxes check for value present onBlur only. If a required value is missing, change input box state to Error
- [ ] Check for unique value in Title input box onBlur only
- [ ] If Title check returns the value is not unique , present an error in-line "This title is already in use" - Do not allow user to submit the form until the value is valid (onBlur only)
- [ ] Validate URL format onBlur only in EndpointURL input box
- [ ] Any submission errors encountered onSubmit should result in an error call out present on the page (OUICallout) as well as in-line error if error is related to any inputs in the error state - main scenario API/create failure. Other scenarios to be discovered. 

onBlur errors:
![image](https://user-images.githubusercontent.com/105819041/194137488-6b14e42c-7c66-430c-9940-b90c70d54b56.png)

onSubmit errors (extremely unlikely because we prevent user from submitting the form if errors are active): 
![image](https://user-images.githubusercontent.com/105819041/194137338-d214c537-1d66-45e5-b7c0-4734dfcf6718.png)

onSubmit API / Save error not related to form input values:
![image](https://user-images.githubusercontent.com/105819041/194137742-e9c475e1-417b-4e8a-b7fd-40e0bd3f21dc.png)

**Comment by KrooshalUX** [comment]
Updated to remove onBlur as Reacts onChange works more similarly to onInput @mpabba3003  thank you for calling this out

**Comment by mpabba3003** [comment]
call out will never show up as we do not allow user to submit (button disabled) until the form is valid.
