### ISSUE TITLE
Update selection UI with EUISelectable + EUIFieldSearch

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/ux#40]
Created a hybrid approach for release speed and somewhat improved user experience. Marking for improvement in 2.5 release.

- [ ] Use [EUISelectable](https://eui.elastic.co/v34.6.0/#/forms/selectable) to allow user to find existing data sources.
- [ ] Use EUIFieldSearch to allow users to search for an existing data source
- [ ] If no external data source connections have been made, disable the radio button and have Default selected by default OR present a button for creation, which should open in a new tab. 

![image](https://user-images.githubusercontent.com/105819041/194183220-6dd5121a-c75d-4608-9316-211ba4314b51.png)

![image](https://user-images.githubusercontent.com/105819041/194183224-3a4eea7d-9cc4-4a51-bb4a-ed37ffd4e45e.png)

**Comment by KrooshalUX** [comment]
For speed I imagine the best approach for the case where there are no external data source connections set up is to disable the radio button like this: 

![image](https://user-images.githubusercontent.com/105819041/194183394-44a62b86-274a-4399-8baa-a8aeea8f7aef.png)


An alternative which we can do in 2.5 is this, which will aid in the discovery and possible adoption of the (production ready version) feature while helping build the mental model of external data sources and index patterns: 

![image](https://user-images.githubusercontent.com/105819041/194183417-301613d0-f040-4301-99d6-74e3e79d459a.png)
![image](https://user-images.githubusercontent.com/105819041/194183422-e5072ebd-37b8-4ec0-a5ff-e63be2244f97.png)

**Comment by kristenTian** [comment]
Disabling the option with the fast approach might cause confusion on why it's being disabled.

Here is the selectable with no content existing, it is also straightforward that user has none configured:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/105667444/194187870-73ba307d-870c-45ad-be6e-3c8edb29a578.png">
