### ISSUE TITLE
[FEATURE] Tenancy status in role creation flows

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/ux#67]
## Context
The following changes are additional pieces of UX required to support the work outlined by [this initiative](https://github.com/opensearch-project/security-dashboards-plugin/issues/1319) to make tenancy configurable through Dashboards.

### 1. Show tenancy status in role permissions overview
- When a role is selected currently there is a section for tenant permissions. We should add a status column to the table in this section so admin users are aware of the status of tenancy when they are administering tenant permissions.

State when tenancy enabled
![image](https://user-images.githubusercontent.com/113368824/221207513-b64eb74f-ec7d-4c01-a8e9-c6810e28f773.png)

State when tenancy disabled
![image](https://user-images.githubusercontent.com/113368824/221208338-d6e17c0e-e883-40d7-b666-94567dd89a55.png)

----

### 2. Can't edit existing role tenancy permissions when tenancy is disabled
- Users can't make changes to existing tenancy permissions if tenancy is disabled.
- When tenancy is enabled users should be able to edit and add tenant permissions as normal.

Edit permissions when tenancy disabled
![image](https://user-images.githubusercontent.com/113368824/221213569-fb1c305a-47e1-4b1d-a76f-fb33cc504fe7.png)

-----

### 3. No tenancy permission section when creating role if tenancy disabled
- When tenancy is disabled we should not show a tenant permissions section during role creation.
- This section show when tenancy is enabled.

![image](https://user-images.githubusercontent.com/113368824/221211854-bcad9daf-a495-4f50-98d5-4d87256da5a9.png)

----

**Comment by jimishs** [comment]
Thanks Shanil. Here's another suggestion, maybe we simply gray out the tenants that are disabled? Also we can add a hover text that suggests that you can only edit or change mappings for active tenants. 

Thoughts?

**Comment by jimishs** [comment]
What is the current behavior for mockup option 3?
