### ISSUE TITLE
[BUG] Dashboard/Dashboards naming convention in navigation pane & UI

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/ux#68]
### What is the bug?
Inconsistent naming convention in the navigation pane versus UI

### How can one reproduce the bug?
Open OpenSearch Dashboards window, view navigation pane, and then view UI.

### What is the expected behavior?
Naming convention should be consistent. 

### What is your host/environment?
OpenSearch Dashboards v 2.6.0

### Do you have any screenshots?
![Screenshot 2023-03-31 at 1 39 43 PM](https://user-images.githubusercontent.com/105296784/229215199-0dc068e8-e41f-4c06-94e7-e97c3bce5292.png)

### Do you have any additional context?
NA

**Comment by KrooshalUX** [comment]
@vagimeli  can you file this in the OpenSearch Dashboards repo? It is not a UX bug, but agree that it should be updated to be consistent Dashboards > Dashboards

**Comment by vagimeli** [comment]
@KrooshalUX Submitted issue under OpenSearch-Dashboards repo (https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4296)
